### ISSUE TITLE
Smart quote causes evaluator to crash

### ISSUE THREAD

**Issue by fonglh** [Coursemology/evaluator-slave#59]
```
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/json.rb:34:in `encode'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/json.rb:34:in `to_json'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/json/encoding.rb:57:in `to_json'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:224:in `generate'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/json/common.rb:224:in `generate'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/json/encoding.rb:101:in `stringify'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/json/encoding.rb:35:in `encode'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/json/encoding.rb:22:in `encode'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/request.rb:294:in `prepare_request_body'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/request.rb:169:in `block in call'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `instrument'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/request.rb:150:in `call'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/base.rb:133:in `method_missing'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:77:in `block in on_evaluation'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:164:in `instrument'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:76:in `on_evaluation'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:61:in `block in on_allocate'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/result_iterator.rb:40:in `block in each'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/result_iterator.rb:39:in `each'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/flexirest-1.3.24/lib/flexirest/result_iterator.rb:39:in `each'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:60:in `on_allocate'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:27:in `client_loop'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:18:in `loop'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/client.rb:18:in `run'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/cli.rb:27:in `run'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/cli.rb:13:in `start'
  /Users/fonglh/evaluator-slave/lib/coursemology/evaluator/cli.rb:9:in `start'
  bin/evaluator:5:in `<top (required)>'
```

If the input code use a smart code, the error above occurs. This doesn't happen on programming question import, only on code evaluation.

**Comment by fonglh** [comment]
Sample code that causes a failure.

```
def area3(x1, y1, x2, y2, x3, y3):
    s = (magnitude(x1, y1, x2, y2) + magnitude(x1, y1, x3, y3) + magnitude(x2, y2, x3, y23))  # Return area of the triangle using Heron’s formula.
    return sqrt(s * (s - magnitude(x1, y1, x2, y2)) * (s - magnitude(x1, y1, x3, y3)) * (s - magnitude(x2, y2, x3, y23)))
```

If the comment is on a newline, the evaluation does not fail.

**Comment by fonglh** [comment]
Simpler version:

```
def area3(x1, y1, x2, y2, x3, y3):
    s = magnitude(x1, y1)# Return area of the triangle using Heron’s formula.
    return s
```

Perhaps what it needs is a smart quote after a function call.

**Comment by fonglh** [comment]
This works, when `magnitude` is called correctly.

```
def area3(x1, y1, x2, y2, x3, y3):
    a = magnitude(x1, y1, y2, x2) # Return area of the triangle using Heron’s formula.
    return a
```

**Comment by fonglh** [comment]
It seems to depend on whether the test report has the smart quote. This appears in the traceback if a function is called wrongly and is on the same line as the comment.

**Comment by fonglh** [comment]
In flexirest's `prepare_request_body` function, copied below, `@post_params` contains the test report with the smart quote `\xE2\x80\x99` and this causes an exception when `to_json` is run.
